Symphony producers
sul-dlss/ld4p-data-pipeline pull request #36
Opened 2017-09-14 22:27 UTC by jgreben

2017-09-14 22:37 UTC, atz requested changes

2017-09-14 22:37 UTC, atz commented on ReactiveProducers/ReactiveKafkaDumpProducer/src/main/resources/application.conf
> +dataDir=${?ld4pData}
The convention for this ENV variable is now `LD4P_DATA`.  Please update to match.

2017-09-14 22:37 UTC, atz commented on ReactiveProducers/ReactiveKafkaUpdateProducer/src/main/resources/application.conf
> +dataDir=${?ld4pData}
Same here.

2017-09-14 22:55 UTC, atz commented on ReactiveProducers/ReactiveKafkaDumpProducer/src/main/resources/application.conf
> +dataDir=${?ld4pData}
@jgreben Looks like that might be fixed if you just rebase.

2017-09-16 01:22 UTC, Maatary commented
Merged the convention so all good

2017-09-16 01:22 UTC, merged

2017-09-16 01:22 UTC, Maatary commented
Fixed the Convention problem